import assert from 'node:assert/strict';
import vm from 'node:vm';
import { MotionBroadcaster, motionReceiverExpression, mapConcurrent, CODEX_SELECTORS } from '../scripts/injector.mjs';
const flush=()=>new Promise(resolve=>setImmediate(resolve));
let lookups=0;
const view={document:{visibilityState:'visible',querySelector(){lookups++;throw Error('unnecessary shell scan');}},__CODEX_DREAM_SKIN_STATE__:{motionFrames:2,acceptMotionFrame:(frame,revision)=>frame==='jpeg'&&revision==='rev'}};
assert.equal(vm.runInNewContext(motionReceiverExpression('jpeg','rev'),{window:view}).accepted,true);
assert.equal(lookups,0,'steady frames use the verified receiver without querying chat DOM');
view.document.visibilityState='hidden';
assert.equal(vm.runInNewContext(motionReceiverExpression('jpeg','rev'),{window:view}).available,false,'an established background canvas keeps its last frame without decoding');
view.__CODEX_DREAM_SKIN_STATE__.motionFrames=0;
assert.equal(vm.runInNewContext(motionReceiverExpression('jpeg','rev'),{window:view}).available,true,'initial frames can establish a background canvas');
const validDoc={visibilityState:'visible',querySelector:selector=>selector===CODEX_SELECTORS.shell||selector===CODEX_SELECTORS.composer?{}:null,querySelectorAll:()=>[]};
const validFrame={document:validDoc,__CODEX_DREAM_SKIN_STATE__:{motionFrames:2,acceptMotionFrame:()=>true}};
const brokenFrame={get document(){throw Error('SecurityError');}};
const outer={document:{querySelector:()=>null,querySelectorAll:()=>[{contentWindow:validFrame}]},__CODEX_DREAM_SKIN_MOTION_CONTEXT__:{win:brokenFrame,document:{}}};
assert.equal(vm.runInNewContext(motionReceiverExpression('jpeg','rev'),{window:outer}).accepted,true,'an inaccessible old iframe cache must not prevent rediscovery');
assert.equal(outer.__CODEX_DREAM_SKIN_MOTION_CONTEXT__.win,validFrame);
let slowResolve,slowCalls=0,fastCalls=0;
const slow={closed:false,evaluate:()=>{slowCalls++;return new Promise(resolve=>slowResolve=resolve);}};
const fast={closed:false,evaluate:async()=>{fastCalls++;return{available:true,accepted:true};}};
const broadcaster=new MotionBroadcaster(()=>[slow,fast]);
assert.equal(broadcaster.deliver('first','rev'),true);
await flush();
assert.equal(broadcaster.deliver('second','rev'),true);
await flush();
assert.equal(slowCalls,1,'a slow target retains at most one pending frame');
assert.equal(fastCalls,2,'another window continues while the slow target is blocked');
slowResolve({available:true,accepted:true});await flush();
assert.equal(broadcaster.deliver('newest','rev'),true);await flush();
assert.equal(slowCalls,2,'the released target gets the newest frame rather than a backlog');
slowResolve({available:true,accepted:true});await flush();
let visible=false,probes=0;
const background={closed:false,evaluate:async()=>{probes++;return{available:visible,accepted:visible};}};
const idle=new MotionBroadcaster(()=>[background],{probeIntervalMs:0});
idle.deliver('last','rev');await flush();
assert.equal(idle.hasReceivers(),false);await flush();
visible=true;
assert.equal(idle.hasReceivers(),false);await flush();
assert.equal(idle.hasReceivers(),true,'showing a background window resumes through a lightweight probe');
assert.ok(probes<=3,'visibility polling is bounded independently from JPEG fetching');
background.closed=true;
assert.equal(idle.hasReceivers(),false,'closed windows cannot keep the wallpaper pipeline running');
let concurrent=0,maxConcurrent=0;const visited=[];
const results=await mapConcurrent([0,1,2,3,4,5],3,async item=>{
  concurrent++;maxConcurrent=Math.max(maxConcurrent,concurrent);visited.push(item);await flush();concurrent--;
  if(item===1)throw Error('auxiliary target');return item;
});
assert.equal(maxConcurrent,3,'new renderers attach with a bounded number of independent probes');
assert.equal(visited.length,6,'a failed auxiliary target cannot stop other attachments');
assert.equal(results[1].status,'rejected');
assert.equal(results[5].value,5);
console.log('PASS: frame broadcasts are bounded, independent, context-cached and visibility-aware.');
